language: php
php:
  - '7.1'
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
 
